const dashHeaderStats = [
  {
    statSubtitle: "REQUEST RECEIVED",
    statTitle: "16,000",
    onboarderStats: true,
    statArrow: "up",
    statPercent: "3.48",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "far fa-chart-bar",
    statIconColor: "bg-red-500",
  },
  {
    statSubtitle: "ONBOARDED",
    statTitle: "1,700",
    onboarderStats: true,
    statArrow: "up",
    statPercent: "3.48",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "fas fa-chart-pie",
    statIconColor: "bg-lightBlue-500",
  },
  {
    statSubtitle: "SALES",
    statTitle: "92.4CR",
    onboarderStats: true,
    statArrow: "up",
    statPercent: "1.10",
    statPercentColor: "text-emerald-500",
    statDescription: "Since yesterday",
    statIconName: "fas fa-users",
    statIconColor: "bg-pink-500",
  },
  {
    statSubtitle: "CONVERSION",
    statTitle: "10.62%",
    onboarderStats: true,
    statArrow: "up",
    statPercent: "12",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "fas fa-percent",
    statIconColor: "bg-lightBlue-500",
  },
];

const onBoarderHeaderStatsData = [
  {
    statSubtitle: "ORDER RECEIVED",
    onboarderStats: true,
    statTitle: "20,000",
    statArrow: "up",
    statPercent: "3.48",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "far fa-chart-bar",
    statIconColor: "bg-red-500",
  },
  {
    statSubtitle: "Average Order Value",
    onboarderStats: true,
    statTitle: "300",
    statArrow: "up",
    statPercent: "3.48",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "fas fa-chart-pie",
    statIconColor: "bg-lightBlue-500",
  },
  {
    statSubtitle: "SALES",
    onboarderStats: true,
    statTitle: "1.4CR",
    statArrow: "up",
    statPercent: "1.10",
    statPercentColor: "text-emerald-500",
    statDescription: "Since yesterday",
    statIconName: "fas fa-users",
    statIconColor: "bg-pink-500",
  },
  {
    statSubtitle: "REVENUE GROWTH RATE",
    onboarderStats: true,
    statTitle: "10.62%",
    statArrow: "up",
    statPercent: "12",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "fas fa-percent",
    statIconColor: "bg-lightBlue-500",
  },
];

const pendingHeaderStatsData = [
  {
    statSubtitle: "EXPECTED ORDER",
    onboarderStats: false,
    statTitle: "23,000",
    statArrow: "up",
    statPercent: "3.48",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "far fa-chart-bar",
    statIconColor: "bg-red-500",
  },
  {
    statSubtitle: "EXPECTED SALES",
    onboarderStats: false,
    statTitle: "2.4CR",
    statArrow: "up",
    statPercent: "1.10",
    statPercentColor: "text-emerald-500",
    statDescription: "Since yesterday",
    statIconName: "fas fa-users",
    statIconColor: "bg-pink-500",
  },
  {
    statSubtitle: "EXPECTED REVENUE GROWTH RATE",
    onboarderStats: false,
    statTitle: "10.62%",
    statArrow: "up",
    statPercent: "12",
    statPercentColor: "text-emerald-500",
    statDescription: "Since last month",
    statIconName: "fas fa-percent",
    statIconColor: "bg-lightBlue-500",
  },
];

export { dashHeaderStats, onBoarderHeaderStatsData, pendingHeaderStatsData };
