import onboardingStatusTypes from "./onboardingStatusTypes";

const registeredMsmes = [
  {
    id: 1,
    name: "Aarav Textiles",
    logo: "/img/msme/aarav-textiles-logo.png",
    totalRevenue: "$120,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$45,000 USD",
  },
  {
    id: 2,
    name: "Bharat Bakers",
    logo: "/img/msme/bharat-bakers-logo.png",
    totalRevenue: "$80,000 USD",
    onboardingStatus: onboardingStatusTypes.PENDING,
    ondcRevenue: "$20,000 USD",
  },
  {
    id: 3,
    name: "Chennai Crafts",
    logo: "/img/msme/chennai-crafts-logo.png",
    totalRevenue: "$200,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$60,000 USD",
  },
  {
    id: 4,
    name: "Delhi Delights",
    logo: "/img/msme/delhi-delights-logo.png",
    totalRevenue: "$150,000 USD",
    onboardingStatus: onboardingStatusTypes.INPROGRESS,
    ondcRevenue: "$40,000 USD",
  },
  {
    id: 5,
    name: "Elegant Embroidery",
    logo: "/img/msme/elegant-embroidery-logo.png",
    totalRevenue: "$100,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$30,000 USD",
  },
  {
    id: 6,
    name: "FreshFruit",
    logo: "/img/msme/freshfruit-logo.png",
    totalRevenue: "$180,000 USD",
    onboardingStatus: onboardingStatusTypes.PENDING,
    ondcRevenue: "$50,000 USD",
  },
  {
    id: 7,
    name: "Gurgaon Gifts",
    logo: "/img/msme/gurgaon-gifts-logo.png",
    totalRevenue: "$140,000 USD",
    onboardingStatus: onboardingStatusTypes.INPROGRESS,
    ondcRevenue: "$35,000 USD",
  },
  {
    id: 8,
    name: "Hyderabad Handlooms",
    logo: "/img/msme/hyderabad-handlooms-logo.png",
    totalRevenue: "$160,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$48,000 USD",
  },
  {
    id: 9,
    name: "Innovative Ironworks",
    logo: "/img/msme/innovative-ironworks-logo.png",
    totalRevenue: "$220,000 USD",
    onboardingStatus: onboardingStatusTypes.PENDING,
    ondcRevenue: "$65,000 USD",
  },
  {
    id: 10,
    name: "Jaipur Jewels",
    logo: "/img/msme/jaipur-jewels-logo.png",
    totalRevenue: "$190,000 USD",
    onboardingStatus: onboardingStatusTypes.INPROGRESS,
    ondcRevenue: "$55,000 USD",
  },
  {
    id: 11,
    name: "Kerala Kitchen",
    logo: "/img/msme/kerala-kitchen-logo.png",
    totalRevenue: "$130,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$38,000 USD",
  },
  {
    id: 12,
    name: "Luminous Lighting",
    logo: "/img/msme/luminous-lighting-logo.png",
    totalRevenue: "$210,000 USD",
    onboardingStatus: onboardingStatusTypes.PENDING,
    ondcRevenue: "$62,000 USD",
  },
  {
    id: 13,
    name: "Mumbai Makers",
    logo: "/img/msme/mumbai-makers-logo.png",
    totalRevenue: "$170,000 USD",
    onboardingStatus: onboardingStatusTypes.INPROGRESS,
    ondcRevenue: "$49,000 USD",
  },
  {
    id: 14,
    name: "Noida Naturals",
    logo: "/img/msme/noida-naturals-logo.png",
    totalRevenue: "$110,000 USD",
    onboardingStatus: onboardingStatusTypes.COMPLETED,
    ondcRevenue: "$32,000 USD",
  },
  {
    id: 15,
    name: "Pune Packers",
    logo: "/img/msme/pune-packers-logo.png",
    totalRevenue: "$240,000 USD",
    onboardingStatus: onboardingStatusTypes.PENDING,
    ondcRevenue: "$70,000 USD",
  },
];

export default registeredMsmes;
